import "server-only";

import { supabaseAdmin } from "@/lib/supabase/admin";
import { currentPlatformAdmin } from "@/lib/admin/auth";
import { generateOwnerPassword } from "@/lib/provisioning/password";
import { validateRestaurantDraft, type RestaurantDraft } from "@/lib/provisioning/draft";
import {
  AssistantSecretWriteError,
  provisionAssistantForLocation,
} from "@/lib/provisioning/assistant";
import { deleteAssistant, ProvisioningError } from "@/lib/vapi/provision";
import type { LocationRow } from "@/lib/supabase/types";

/* Making a restaurant real, in one operator-initiated act.
 *
 * This is the only place in the product that creates an organization, and
 * the only place that creates a user. Public signup is closed
 * (app/signup/actions.ts) precisely so that this is true: every account
 * on this platform is one the operator agreed to.
 *
 * WHY THE SERVICE ROLE, AND WHAT THAT OBLIGES
 * -------------------------------------------
 * Every other write path in this app runs as the signed-in user through
 * lib/supabase/server.ts, and lets RLS decide what it may touch. That
 * cannot work here, and the reason is structural rather than incidental:
 *
 *   * The rows being written belong to an organization the caller is
 *     deliberately NOT a member of. `org_read`/`location_write` and
 *     friends (supabase/migrations/20260807000200_rls.sql) are all gated
 *     on app.is_org_member, so the operator's own session matches
 *     nothing here -- correctly. A platform admin is not a tenant, and
 *     giving them a membership in every restaurant to make this work
 *     would quietly hand the operator console's identity a seat inside
 *     every customer's data.
 *   * Creating an auth user is not a PostgREST operation at all. It is
 *     Supabase's admin API, which has no RLS to be subject to.
 *
 * So this file holds the service-role key, and with it the whole tenancy
 * boundary. Three rules keep that honest, and each is enforced below
 * rather than merely intended:
 *
 *   1. It refuses to do anything at all unless currentPlatformAdmin()
 *      says the caller is staff. That check runs HERE, not only in the
 *      UI that calls it -- a hidden button is not a permission, and a
 *      server action stays reachable by anyone who can construct the
 *      request once it exists.
 *   2. Nothing it writes is chosen by an untrusted caller. There is no
 *      org id parameter, no user id parameter, no location id parameter:
 *      every id is generated by the database inside this call. A caller
 *      cannot aim any of these writes at Nonna Rosa.
 *   3. Neither the service-role key nor the minted tool secret is ever
 *      returned to the browser. The one secret that does come back is
 *      the owner's password, which the operator must be able to read
 *      once -- see the note on it below.
 *
 * THE PASSWORD
 * ------------
 * Generated here, handed straight to Supabase's createUser, and returned
 * to the caller in this function's own return value so the operator can
 * read it off the screen once. It is never written to a column, never
 * logged, and never stored by us in any form -- Supabase keeps only its
 * own bcrypt hash, exactly as it does for a password a user chose
 * themselves. If the operator loses it before handing it over, the fix
 * is a password reset, not a lookup: there is nowhere to look.
 *
 * ATOMICITY
 * ---------
 * PostgREST gives no transaction across these calls, so this does the
 * next best thing: it orders the work so the likeliest failure happens
 * first and cheapest, and it compensates on failure by deleting what it
 * made. Every id it deletes is one it generated moments earlier in this
 * same call, so a rollback can never reach a row that was already there.
 */

export type CreatedRestaurant = {
  organizationId: string;
  locationId: string;
  locationName: string;
  assistantId: string;
  ownerEmail: string;
  /** Shown to the operator exactly once, then gone. Never persisted. */
  ownerPassword: string;
  /** What still stands between this restaurant and a ringing phone. */
  stillMissing: string[];
};

export type CreateRestaurantResult =
  | { ok: true; restaurant: CreatedRestaurant }
  | { ok: false; error: string };

/** Undo, in reverse order of creation. Deliberately best-effort and
 *  deliberately loud in the log: a rollback that itself fails leaves
 *  something for a human to find, and saying which id is the only way
 *  they will find it. */
async function rollback({
  organizationId,
  authUserId,
  assistantId,
  vapiKey,
}: {
  organizationId: string | null;
  authUserId: string | null;
  assistantId: string | null;
  vapiKey: string;
}) {
  if (assistantId) {
    try {
      await deleteAssistant(vapiKey, assistantId);
    } catch (err) {
      console.error(
        "[provisioning] rollback could not delete Vapi assistant",
        assistantId,
        err instanceof Error ? err.message : err,
      );
    }
  }

  // Deleting the organization cascades to its location, hours, menu
  // categories, menu items and membership -- every one of those tables
  // is ON DELETE CASCADE from organizations or locations
  // (supabase/migrations/20260807000100_schema.sql).
  if (organizationId) {
    const { error } = await supabaseAdmin().from("organizations").delete().eq("id", organizationId);
    if (error) {
      console.error("[provisioning] rollback could not delete organization", organizationId, {
        code: error.code,
      });
    }
  }

  if (authUserId) {
    const { error } = await supabaseAdmin().auth.admin.deleteUser(authUserId);
    if (error) {
      console.error("[provisioning] rollback could not delete auth user", authUserId, error.message);
    }
  }
}

export async function createRestaurant(
  draft: RestaurantDraft,
  { base }: { base: string },
): Promise<CreateRestaurantResult> {
  // ── the gate ───────────────────────────────────────────────────────
  //
  // First statement in the function, before a single value from `draft`
  // is looked at, let alone written. currentPlatformAdmin() revalidates
  // the token with Supabase (getUser, not getSession) and reads
  // platform_admins with the service role, failing closed on any error.
  const admin = await currentPlatformAdmin();
  if (!admin) {
    // The same answer a restaurant owner gets, a signed-out stranger
    // gets, and a signed-in user poking at this action gets. It names
    // nothing about whether the action exists or what it would need.
    return { ok: false, error: "Not found." };
  }

  const checked = validateRestaurantDraft(draft);
  if (!checked.ok) return { ok: false, error: checked.error };
  const value = checked.value;

  const vapiKey = process.env.VAPI_PRIVATE_KEY;
  if (!vapiKey) {
    console.error("[provisioning] VAPI_PRIVATE_KEY is not configured");
    return {
      ok: false,
      error:
        "This deployment cannot create AI assistants: VAPI_PRIVATE_KEY is not set. Nothing was " +
        "created.",
    };
  }

  const supabase = supabaseAdmin();

  let authUserId: string | null = null;
  let organizationId: string | null = null;
  let assistantId: string | null = null;

  try {
    // ── 1. the owner's login ─────────────────────────────────────────
    //
    // First, on purpose. The likeliest way this whole action fails is an
    // email that already has an account, and finding that out before
    // anything is written means there is nothing to roll back.
    //
    // email_confirm: true because there is no confirmation email to
    // wait on -- the operator hands these credentials over in person or
    // over the phone, and an owner who cannot sign in until they find a
    // confirmation link is an owner who calls the operator instead.
    const password = generateOwnerPassword();
    const created = await supabase.auth.admin.createUser({
      email: value.ownerEmail,
      password,
      email_confirm: true,
    });

    if (created.error || !created.data.user) {
      // Never log `password`, and never log the whole error object --
      // Supabase echoes the request body back on some failures.
      console.error("[provisioning] could not create the owner's auth user", created.error?.message);
      const already = created.error?.message?.toLowerCase().includes("already");
      return {
        ok: false,
        error: already
          ? `${value.ownerEmail} already has an account. Use a different email, or add this ` +
            "restaurant to their existing one by hand."
          : "Could not create the owner's login. Check the email and try again. Nothing was created.",
      };
    }
    authUserId = created.data.user.id;

    // ── 2. the organization and its owner's membership ───────────────
    const org = await supabase
      .from("organizations")
      .insert({ name: value.name })
      .select("id")
      .single();

    if (org.error || !org.data) {
      console.error("[provisioning] could not create the organization", { code: org.error?.code });
      await rollback({ organizationId: null, authUserId, assistantId: null, vapiKey });
      return { ok: false, error: "Could not create the restaurant. Nothing was created." };
    }
    organizationId = org.data.id as string;

    // An organization with no members is invisible to every RLS policy
    // in the database -- unreadable and unwritable by anyone, including
    // the person who just paid for it. The membership is what makes the
    // row above mean anything, so it goes in immediately.
    const membership = await supabase
      .from("memberships")
      .insert({ user_id: authUserId, org_id: organizationId, role: "owner" });

    if (membership.error) {
      console.error("[provisioning] could not create the owner's membership", {
        code: membership.error.code,
      });
      await rollback({ organizationId, authUserId, assistantId: null, vapiKey });
      return { ok: false, error: "Could not attach the owner to the restaurant. Nothing was created." };
    }

    // ── 3. the location ──────────────────────────────────────────────
    //
    // onboarding_step is written as 'menu', its furthest value: the
    // operator collected everything the old owner-facing wizard used to
    // walk through, so there is no half-finished step for anyone to
    // resume. Nothing reads it once agent_secret_hash is set, which
    // step 5 does below.
    const location = await supabase
      .from("locations")
      .insert({
        org_id: organizationId,
        name: value.name,
        address: value.address,
        timezone: value.timezone,
        business_phone: value.businessPhone,
        fallback_human_number: value.fallbackNumber,
        tax_rate_bps: value.taxRateBps,
        order_types: value.orderTypes,
        pickup_promise_minutes: value.pickupPromiseMinutes,
        delivery_promise_minutes: value.deliveryPromiseMinutes,
        seats: value.seats,
        max_party_size: value.maxPartySize,
        reservation_slot_minutes: value.reservationSlotMinutes,
        onboarding_step: "menu",
      })
      .select("*")
      .single();

    if (location.error || !location.data) {
      console.error("[provisioning] could not create the location", { code: location.error?.code });
      await rollback({ organizationId, authUserId, assistantId: null, vapiKey });
      return { ok: false, error: "Could not create the location. Nothing was created." };
    }
    const locationRow = location.data as LocationRow;

    // ── 4. hours and menu ────────────────────────────────────────────
    const hoursRows = value.hours.map((h) => ({ ...h, location_id: locationRow.id }));
    const hours = await supabase.from("hours").insert(hoursRows);
    if (hours.error) {
      console.error("[provisioning] could not save hours", { code: hours.error.code });
      await rollback({ organizationId, authUserId, assistantId: null, vapiKey });
      return { ok: false, error: "Could not save the hours. Nothing was created." };
    }

    for (const [index, category] of value.menu.entries()) {
      const categoryRow = await supabase
        .from("menu_categories")
        .insert({ location_id: locationRow.id, name: category.name, sort_order: index })
        .select("id")
        .single();

      if (categoryRow.error || !categoryRow.data) {
        console.error("[provisioning] could not save a menu category", {
          code: categoryRow.error?.code,
        });
        await rollback({ organizationId, authUserId, assistantId: null, vapiKey });
        return { ok: false, error: `Could not save the "${category.name}" category. Nothing was created.` };
      }

      if (category.items.length === 0) continue;

      // menu_items.location_id is denormalised and kept honest by a
      // trigger that derives it from the category, so it is deliberately
      // not sent here -- see app.sync_menu_item_location.
      const items = await supabase.from("menu_items").insert(
        category.items.map((item, itemIndex) => ({
          category_id: categoryRow.data.id,
          name: item.name,
          description: item.description,
          price_cents: item.priceCents,
          sort_order: itemIndex,
        })),
      );

      if (items.error) {
        console.error("[provisioning] could not save menu items", { code: items.error.code });
        await rollback({ organizationId, authUserId, assistantId: null, vapiKey });
        return { ok: false, error: `Could not save the items in "${category.name}". Nothing was created.` };
      }
    }

    // ── 5. the tool secret and the Vapi assistant ────────────────────
    //
    // The one shared implementation, the same one the CLI script rests
    // on. It mints the secret, creates the assistant, then writes only
    // the hash -- in that order, for the reason its own header gives.
    let secretAndAssistant: { secret: string; assistantId: string };
    try {
      secretAndAssistant = await provisionAssistantForLocation({
        location: locationRow,
        hours: value.hours,
        base,
        vapiKey,
      });
      assistantId = secretAndAssistant.assistantId;
    } catch (err) {
      if (err instanceof AssistantSecretWriteError) assistantId = err.assistantId;
      console.error(
        "[provisioning] assistant provisioning failed",
        err instanceof Error ? err.message : err,
      );
      await rollback({ organizationId, authUserId, assistantId, vapiKey });
      return {
        ok: false,
        error:
          err instanceof ProvisioningError
            ? `Could not create the AI assistant: ${err.message} Nothing was created.`
            : "Could not create the AI assistant. Nothing was created.",
      };
    }

    // The plaintext tool secret dies here, on purpose. It belongs in the
    // Vapi assistant's own tool headers -- which step 5 just put it in --
    // and its hash belongs in the location row. There is no third place
    // for it, and specifically not this function's return value: nothing
    // the operator does by hand needs it, and anything that did would be
    // a reason to rotate it rather than to display it.

    return {
      ok: true,
      restaurant: {
        organizationId,
        locationId: locationRow.id,
        locationName: locationRow.name,
        assistantId: secretAndAssistant.assistantId,
        ownerEmail: value.ownerEmail,
        ownerPassword: password,
        stillMissing: whatIsMissing(locationRow, value.menu.length),
      },
    };
  } catch (err) {
    // Anything unforeseen -- a network failure mid-write, a thrown
    // Supabase client error -- lands here rather than leaving a
    // half-made restaurant behind.
    console.error("[provisioning] unexpected failure", err instanceof Error ? err.message : err);
    await rollback({ organizationId, authUserId, assistantId, vapiKey });
    return { ok: false, error: "Something went wrong creating this restaurant. Nothing was created." };
  }
}

/** What is still true of a restaurant the moment it is created, and has
 *  to stop being true before a caller can reach the assistant. Buying a
 *  phone number is deliberately not part of this action -- it spends
 *  money, so it stays a separate, deliberate button. */
function whatIsMissing(location: LocationRow, categoryCount: number): string[] {
  const missing = [
    "No phone number yet -- buying one is a separate step, because it spends money.",
    "Forwarding is not verified, so the restaurant's own line will not hand calls over yet.",
    "This location is not marked live, so the assistant will not answer.",
  ];
  if (categoryCount === 0) {
    missing.push(
      "The menu is empty -- the assistant can answer hours and take messages, but it cannot " +
        "take an order until somebody adds items.",
    );
  }
  if (!location.business_phone) {
    missing.push("No display phone on file (optional -- it is only what the dashboard shows).");
  }
  return missing;
}
