"use client";

import { useActionState } from "react";
import { useFormStatus } from "react-dom";
import { Corners } from "./Corners";
import { setOwnPassword, type SetPasswordState } from "@/app/set-password/actions";
import { MINIMUM_PASSWORD_LENGTH } from "@/lib/auth/must-change-password";

function Submit() {
  const { pending } = useFormStatus();
  return (
    <button type="submit" className="btn btn-primary btn-block" disabled={pending}>
      {pending ? "One moment…" : "Set my password"}
    </button>
  );
}

/** Deliberately the login card, one field longer. This is the second
 *  screen anyone at a new restaurant ever sees, seconds after the first,
 *  and it is asking them to do something they did not expect -- looking
 *  like a different product would be the last thing it should do. */
export function SetPasswordForm({ email }: { email: string }) {
  const [state, action] = useActionState<SetPasswordState, FormData>(setOwnPassword, {});

  return (
    <div className="card blueprint auth-card">
      <Corners />

      <div className="auth-why">
        <strong>Choose a password only you know.</strong> The one you signed in with was
        generated by Dialtone and handed to you, so somebody here has seen it. It stops working
        the moment you pick your own.
      </div>

      <form action={action} className="auth-form">
        {/* Not editable, and not sent -- the server reads the email off
            the session. It is here so a password manager files this under
            the right account. */}
        <input type="hidden" name="username" autoComplete="username" value={email} readOnly />

        <div className="field">
          <label htmlFor="new-password">New password</label>
          <input
            id="new-password"
            className="input"
            type="password"
            name="password"
            autoComplete="new-password"
            minLength={MINIMUM_PASSWORD_LENGTH}
            required
            autoFocus
          />
          <p className="text-muted auth-note">
            At least {MINIMUM_PASSWORD_LENGTH} characters.
          </p>
        </div>

        <div className="field">
          <label htmlFor="confirm-password">Type it again</label>
          <input
            id="confirm-password"
            className="input"
            type="password"
            name="confirm"
            autoComplete="new-password"
            minLength={MINIMUM_PASSWORD_LENGTH}
            required
          />
        </div>

        <Submit />
      </form>

      {state.error ? <p className="auth-error">{state.error}</p> : null}

      <p className="text-muted auth-note">
        Signed in as {email}. Nothing else in Dialtone opens until this is done.
      </p>
    </div>
  );
}
