import { describe, expect, it } from "vitest";
import {
  MINIMUM_PASSWORD_LENGTH,
  MUST_CHANGE_PASSWORD_CLAIM,
  SET_PASSWORD_PATH,
  mustChangePassword,
  reachableWithTemporaryPassword,
} from "./must-change-password";

/* The flag, and the choice of where to keep it.
 *
 * Every restaurant's first password was generated by an operator and read
 * off a screen, so for as long as it is unchanged there is a second person
 * who can sign in as that restaurant. The flag is what makes that state
 * temporary; if its subject can clear it, the flag is decoration.
 *
 * Supabase hands every auth user two metadata bags. `user_metadata` is
 * writable by the user -- one `auth.updateUser({ data: {...} })` with the
 * anon key and their own token. `app_metadata` needs the service-role
 * key. The test below is the one that matters: it fails the moment
 * somebody "simplifies" this predicate into reading either bag. */

describe("where the flag is read from", () => {
  it("believes app_metadata", () => {
    expect(mustChangePassword({ app_metadata: { [MUST_CHANGE_PASSWORD_CLAIM]: true } })).toBe(true);
  });

  it("ignores the same flag in user_metadata, which the owner can write themselves", () => {
    const forged = {
      app_metadata: {},
      user_metadata: { [MUST_CHANGE_PASSWORD_CLAIM]: true },
    } as { app_metadata: Record<string, unknown> };

    expect(mustChangePassword(forged)).toBe(false);
  });

  it("cannot be cleared by anything the account itself can write", () => {
    // The other direction of the same point: an owner who sets
    // must_change_password:false in their own user_metadata is still
    // flagged, because that bag is not consulted.
    const stillFlagged = {
      app_metadata: { [MUST_CHANGE_PASSWORD_CLAIM]: true },
      user_metadata: { [MUST_CHANGE_PASSWORD_CLAIM]: false },
    };

    expect(mustChangePassword(stillFlagged)).toBe(true);
  });

  it.each([
    ["absent", {}],
    ["cleared to null, which is how the change action removes it", { [MUST_CHANGE_PASSWORD_CLAIM]: null }],
    ["explicitly false", { [MUST_CHANGE_PASSWORD_CLAIM]: false }],
    ["a truthy string rather than the boolean", { [MUST_CHANGE_PASSWORD_CLAIM]: "true" }],
  ])("does not flag an account whose claim is %s", (_case, app_metadata) => {
    expect(mustChangePassword({ app_metadata })).toBe(false);
  });

  it.each([
    ["signed out", null],
    ["undefined", undefined],
    ["carrying no metadata at all", { app_metadata: null }],
  ])("treats %s as not flagged, so a stranger is not sent to set a password", (_case, user) => {
    expect(mustChangePassword(user)).toBe(false);
  });
});

describe("what a flagged account may still load", () => {
  it.each([
    "/dashboard",
    "/dashboard/calls",
    "/dashboard/calls/8f0f8c6e-0000-0000-0000-000000000000",
    "/dashboard/orders",
    "/dashboard/menu",
    "/dashboard/menu/live",
    "/dashboard/messages",
    "/dashboard/settings",
    "/admin",
    "/admin/new",
    "/login",
    "/",
  ])("not %s", (pathname) => {
    expect(reachableWithTemporaryPassword(pathname)).toBe(false);
  });

  it("the screen it is being sent to, or the redirect would loop", () => {
    expect(reachableWithTemporaryPassword(SET_PASSWORD_PATH)).toBe(true);
  });

  it("the magic-link exchange, which has to be able to finish making the session", () => {
    expect(reachableWithTemporaryPassword("/auth/callback")).toBe(true);
  });

  it.each(["/api/agent/order", "/api/twilio/voice"])(
    "%s, which carries the agent's own credential and no browser cookie",
    (pathname) => {
      // A redirect here would answer a live phone call with a 307. These
      // routes authenticate on a secret this user does not hold, so the
      // exemption grants nothing: being past the gate is not being
      // authorised.
      expect(reachableWithTemporaryPassword(pathname)).toBe(true);
    },
  );

  it("does not exempt a dashboard path that merely starts with the same letters", () => {
    expect(reachableWithTemporaryPassword("/set-password-please")).toBe(false);
    expect(reachableWithTemporaryPassword("/apifake")).toBe(false);
  });
});

describe("the minimum length", () => {
  it("is longer than Supabase's own default of six", () => {
    expect(MINIMUM_PASSWORD_LENGTH).toBeGreaterThan(6);
  });
});
