import { NextResponse, type NextRequest } from "next/server";
import { createServerClient } from "@supabase/ssr";
import { supabaseEnv } from "./env";
import {
  SET_PASSWORD_PATH,
  mustChangePassword,
  reachableWithTemporaryPassword,
} from "@/lib/auth/must-change-password";

/** Refreshes the auth cookie on every request, gates /dashboard, and
 *  gates everything on an account having a password its operator does not
 *  know. */
export async function updateSession(request: NextRequest) {
  let response = NextResponse.next({ request });

  const { url, anonKey } = supabaseEnv();

  const supabase = createServerClient(url, anonKey, {
    cookies: {
      getAll: () => request.cookies.getAll(),
      setAll: (items) => {
        items.forEach(({ name, value }) => request.cookies.set(name, value));
        response = NextResponse.next({ request });
        items.forEach(({ name, value, options }) =>
          response.cookies.set(name, value, options),
        );
      },
    },
  });

  // getUser() revalidates the token with Supabase. getSession() only reads
  // the cookie, which a client can forge — do not swap it in here.
  const {
    data: { user },
  } = await supabase.auth.getUser();

  const { pathname } = request.nextUrl;
  // /admin is deliberately absent: app/admin/layout.tsx answers a
  // non-admin with notFound() rather than a redirect, so that a signed-in
  // restaurant owner poking at it cannot tell the route exists. Sending
  // them to /login from here would tell them.
  const isProtected = pathname.startsWith("/dashboard") || pathname === SET_PASSWORD_PATH;

  if (!user && isProtected) {
    const to = request.nextUrl.clone();
    to.pathname = "/login";
    to.searchParams.set("next", pathname);
    return NextResponse.redirect(to);
  }

  // Every restaurant's first password was generated by the operator and
  // read off a screen, so for as long as it is unchanged the operator
  // knows it. Until the owner replaces it, this account can sign in and
  // reach nothing else -- not the dashboard, not the calls, not the menu.
  //
  // The check belongs here rather than on the page it sends people to.
  // Guarding /set-password's own screen would gate the one route the
  // owner is supposed to see and leave every other one open; this way a
  // typed-in /dashboard/menu is caught by the same line as everything
  // else. What it cannot cover is the server actions -- middleware sees
  // the POST, but a refusal there is a redirect a client may or may not
  // follow -- so those refuse for themselves via lib/auth/password-gate.
  if (user && mustChangePassword(user) && !reachableWithTemporaryPassword(pathname)) {
    const to = request.nextUrl.clone();
    to.pathname = SET_PASSWORD_PATH;
    to.search = "";
    return NextResponse.redirect(to);
  }

  // And the other direction: nobody who has already set their own
  // password should be able to land back on a screen that insists they
  // have not.
  if (user && !mustChangePassword(user) && pathname === SET_PASSWORD_PATH) {
    const to = request.nextUrl.clone();
    to.pathname = "/dashboard";
    to.search = "";
    return NextResponse.redirect(to);
  }

  if (user && (pathname === "/login" || pathname === "/signup")) {
    const to = request.nextUrl.clone();
    to.pathname = "/dashboard";
    to.search = "";
    return NextResponse.redirect(to);
  }

  return response;
}
